### GET Employee
GET http://localhost:3000/employees/3


### CREATE Employee
POST http://localhost:3000/employees
Content-Type: application/json

{
    "name": "Mr. Employee",
    "managerId": 2,
    "contactInfo": {
            "email": "employee.dell.com",
            "phone": "+55539823327"
        }
}

### UPDATE Employee
PATCH  http://localhost:3000/employees/3
Content-Type: application/json

{
    "name": "Mr. JOE",
    "managerId": 1,
    "contactInfo": {
            "email": "mudei@dell.com",
            "phone": "+999999999"
        }
}

### ASSIGN Manager
PATCH  http://localhost:3000/employees/3/assign-manager
Content-Type: application/json

{
    "managerId": 2
}